name: DeployToGitHubPages
env:
  PUBLISH_DIR: bin/Release/net7.0/publish/wwwroot
  # Include subfolders if needed

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Publish app
      run: dotnet publish -c Release
      # You can use cd before if your project is in a subfolder
        
    - name: Deploy to Github Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: main
        BRANCH: gh-pages
        FOLDER: ${{ env.PUBLISH_DIR }}
        CLEAN: true
